name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: terraform

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint-terraform:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.0

      - name: Terraform fmt
        run: terraform fmt -recursive -check

  plan-terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    needs: lint-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.0

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: 0.40.2

      - name: Set up AWS configuration file
        run: |
          # shellcheck disable=SC2086
          sed -i "s/__AWS_ACCESS_KEY_ID__/${{ secrets.AWS_ACCESS_KEY_ID }}/g" ${{ github.workspace }}/.github/aws-config
          # shellcheck disable=SC2086
          sed -i "s/__AWS_SECRET_ACCESS_KEY__/${{ secrets.AWS_SECRET_ACCESS_KEY }}/g" ${{ github.workspace }}/.github/aws-config
          echo "AWS_CONFIG_FILE=${{ github.workspace }}/.github/aws-config" >> $GITHUB_ENV

      - name: Terragrunt run-all init
        run: terragrunt run-all init

      - name: Terragrunt run-all plan
        run: terragrunt run-all plan

      - name: Terragrunt run-all apply
        if: github.ref == 'refs/heads/main'
        run: terragrunt run-all apply
